/*
Copyright 2025 The Grove Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corev1alpha1 "github.com/ai-dynamo/grove/operator/api/core/v1alpha1"
	scheme "github.com/ai-dynamo/grove/operator/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TopologyDomainsGetter has a method to return a TopologyDomainInterface.
// A group's client should implement this interface.
type TopologyDomainsGetter interface {
	TopologyDomains() TopologyDomainInterface
}

// TopologyDomainInterface has methods to work with TopologyDomain resources.
type TopologyDomainInterface interface {
	Create(ctx context.Context, topologyDomain *corev1alpha1.TopologyDomain, opts v1.CreateOptions) (*corev1alpha1.TopologyDomain, error)
	Update(ctx context.Context, topologyDomain *corev1alpha1.TopologyDomain, opts v1.UpdateOptions) (*corev1alpha1.TopologyDomain, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1alpha1.TopologyDomain, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1alpha1.TopologyDomainList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1alpha1.TopologyDomain, err error)
	TopologyDomainExpansion
}

// topologyDomains implements TopologyDomainInterface
type topologyDomains struct {
	*gentype.ClientWithList[*corev1alpha1.TopologyDomain, *corev1alpha1.TopologyDomainList]
}

// newTopologyDomains returns a TopologyDomains
func newTopologyDomains(c *GroveV1alpha1Client) *topologyDomains {
	return &topologyDomains{
		gentype.NewClientWithList[*corev1alpha1.TopologyDomain, *corev1alpha1.TopologyDomainList](
			"topologydomains",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1alpha1.TopologyDomain { return &corev1alpha1.TopologyDomain{} },
			func() *corev1alpha1.TopologyDomainList { return &corev1alpha1.TopologyDomainList{} },
		),
	}
}
