# Workload: EC2 - Insufficient Topology Domains
# Test scenario: No PCS constraint, PCSG with rack constraint and replicas=5 (need 5 racks but only have 2)
---
apiVersion: grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: tas-insufficient-domains
  labels:
    app: tas-insufficient-domains
spec:
  replicas: 1
  template:
    podCliqueScalingGroups:
      - name: workers
        replicas: 5
        minAvailable: 5
        topologyConstraint:
          packDomain: rack
        cliqueNames:
          - worker
    cliques:
      - name: worker
        labels:
          kai.scheduler/queue: test
        spec:
          roleName: worker
          replicas: 1
          minAvailable: 1
          podSpec:
            schedulerName: kai-scheduler
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node_role.e2e.grove.nvidia.com
                          operator: In
                          values:
                            - agent
            tolerations:
              - key: node_role.e2e.grove.nvidia.com
                operator: Equal
                value: agent
                effect: NoSchedule
            containers:
              - name: worker
                image: registry:5001/nginx:alpine-slim
                resources:
                  requests:
                    memory: 30Mi
