# Workload: SP7 - Multi-Clique with Different Constraints
# Test scenario: PCSG with block constraint, worker PCLQ with host constraint, router PCLQ with rack constraint
---
apiVersion: grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: tas-multi-clique
  labels:
    app: tas-multi-clique
spec:
  replicas: 1
  template:
    podCliqueScalingGroups:
      - name: inference-group
        replicas: 1
        minAvailable: 1
        topologyConstraint:
          packDomain: block
        cliqueNames:
          - worker
          - router
    cliques:
      - name: worker
        labels:
          kai.scheduler/queue: test
        topologyConstraint:
          packDomain: host
        spec:
          roleName: worker
          replicas: 2
          minAvailable: 2
          podSpec:
            schedulerName: kai-scheduler
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node_role.e2e.grove.nvidia.com
                          operator: In
                          values:
                            - agent
            tolerations:
              - key: node_role.e2e.grove.nvidia.com
                operator: Equal
                value: agent
                effect: NoSchedule
            containers:
              - name: worker
                image: registry:5001/nginx:alpine-slim
                resources:
                  requests:
                    memory: 30Mi
      - name: router
        labels:
          kai.scheduler/queue: test
        topologyConstraint:
          packDomain: rack
        spec:
          roleName: router
          replicas: 2
          minAvailable: 2
          podSpec:
            schedulerName: kai-scheduler
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node_role.e2e.grove.nvidia.com
                          operator: In
                          values:
                            - agent
            tolerations:
              - key: node_role.e2e.grove.nvidia.com
                operator: Equal
                value: agent
                effect: NoSchedule
            containers:
              - name: router
                image: registry:5001/nginx:alpine-slim
                resources:
                  requests:
                    memory: 30Mi
